### ISSUE TITLE
Dźwięki

### ISSUE THREAD

**Issue by Kacperacy** [skni-kod/roguelike#178]
Zróbcie dźwięki chodzenia bicia i tego typu rzeczy.

**Comment by CyberSer69** [comment]
## Efekty dźwiękowe v1
- chodzenie
- bicie
- cięcie (np. mieczem)
- tworzenie spella (np. fireball) [coś tego typu](https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/ce/Evoker_cast1.ogg/revision/latest?cb=20190501074917) lub [to](https://www.soundsnap.com/ancient_game_magic_wand_cast_poof_wav)
- otrzymanie obrażeń
